[package]
name = "intermediate"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14.10", features = ["full"] }
tokio = { version = "1.8.2", features = ["full"] }
lazy_static = "1.4.0"
futures = "0.3.15"
unicase = "2.6.0"
serde = { version = "1.0.126", features = ["derive"]}