/* SQL("""SELECT e.ID_COLOCACION, p.NOMBRE || ' ' || p.PRIMER_APELLIDO || ' ' || p.SEGUNDO_APELLIDO AS NOMBRE, SUM(e.ABONO_ANTICIPADO) AS ANTICIPADO, SUM(e.ABONO_CXC) AS CAUSADO, SUM(ABONO_SERVICIOS) AS SERVICIO, SUM(ABONO_MORA) AS MORA FROM "col$extracto" e
LEFT JOIN "col$colocacion" c ON c.ID_COLOCACION = e.ID_COLOCACION 
LEFT JOIN "gen$persona" p ON p.ID_IDENTIFICACION = c.ID_IDENTIFICACION AND p.ID_PERSONA = c.ID_PERSONA 
WHERE e.FECHA_EXTRACTO BETWEEN {fecha_inicial} AND {fecha_final}
GROUP BY e.ID_COLOCACION, p.NOMBRE, p.PRIMER_APELLIDO, p.SEGUNDO_APELLIDO
HAVING SUM(e.ABONO_ANTICIPADO) <> 0 OR SUM(e.ABONO_CXC) <> 0 OR SUM(ABONO_SERVICIOS)  <> 0 OR SUM(ABONO_MORA) <> 0""")" +
*/